### ISSUE TITLE
Организация проекта

### ISSUE THREAD

**Issue by mglknFSD** [evgeny1993r/toxin#47]
Обычно файлы проекта делят например следующим образом:

`src`       - скрипты и стили проекта
`assets` - всевозможные статические файлы (картинки, шрифты...). Все файлы которые мы решили что им не место в `src`
`configs` - сюда помещаем разные строки которые мы решили не хардкодить в проект, конфигурационные файлы webpack-а postcss и прочие.

Тут могут быть вариации, например конфиги webpack-а могут и в корне проекта лежать, это привычно для большинства небольших проектов, но в структуре папок проекта должна быть логика понятная любому разработчику.

Вот я захожу в твой проект.

![Screenshot 2021-06-05 at 16 01 36](https://user-images.githubusercontent.com/75975369/120892500-50f96080-c617-11eb-8658-283b4873a391.png)

В корне я вижу непонятную папку `PP` (ее название мне ни чем не говорит) в которой лежат картинки. В `src` лежат папки `images` (а PP зачем), `fonts`. В `public` я вижу файл с расширение `.pug` (в public обычно помещают публичные файлы - она так и называется public - картинки что бы их раздавать как статичные ресурсы).

В общем надо навести порядок.

**Comment by mglknFSD** [comment]
Я так и не понял зачем нужна папка PixelPerfect. Поясни пожалуйста.

**Comment by evgeny1993r** [comment]
Папка PixelPerfect - хранит в себе изображения, которые нужны для проверки верстки в pixel perfect. Удалить?

**Comment by mglknFSD** [comment]
> 
> 
> Папка PixelPerfect - хранит в себе изображения, которые нужны для проверки верстки в pixel perfect. Удалить?

Это нужно вам, для разработки, в проекте они ни к чему.
